### ISSUE TITLE
The Idris REPL opens then exits when I run ‘docker run dgellow/idris idris’

### ISSUE THREAD

**Issue by neatville** [dgellow/idris-docker-image#1]
My OS is Antergos (Arch) Linux if that makes any difference, though I have yet to test it out elsewhere.  
After adding the help flag, I cant see anything else that should open it and keep it that way. The ide-mode option repeated the same error over and over again (can’t remember at the moment, I am on mobile).

**Comment by dgellow** [comment]
Hi @neatville,

Have you tried to run it with the flags `-i` (interactive, keep STDIN open) and `-t` (allocate a pseudo-tty)? That's necessary when running interactive programs using docker. 

```
$ docker run -it dgellow/idris idris
```
