### ISSUE TITLE
I guess Idris 2 image needs Chez scheme to be installed

### ISSUE THREAD

**Issue by stereobooster** [dgellow/idris-docker-image#2]
```Docker
FROM dgellow/idris2

RUN \
  apt-get update -y && \
  apt-get install -y chezscheme

RUN echo 'export PATH=/root/.idris2/bin/:$PATH' >>~/.bashrc
RUN echo 'alias idris=idris2' >>~/.bashrc
```

It's not a big deal - I can add it myself. But it would be nice if it comes built in. Idris2 can't build without scheme

PS I'm using it here https://github.com/stereobooster/idris-vscode-remote-development-template

**Comment by dgellow** [comment]
Thanks, I think that may solve some issues I faced last time as I tried to fix this image. If you want to create a PR, I can merge it. Otherwise I will take some time during the weekend and see how your suggestion goes.

**Comment by dgellow** [comment]
Should be good with https://github.com/dgellow/idris-docker-image/commit/25335de7985e227687405f68e81958f7578ed26f!
